version: "3"
services:
  mongo:
    image: mongo:8
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  node:
    build: .
    container_name: go_fast_node
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/go_fast
      - JWT_SECRET
      - EMAIL_USER
      - EMAIL_PASS
    depends_on:
      - mongo

volumes:
  mongo_data:
